config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", include("talks_tue.core.urls", namespace="core")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("talks_tue.users.urls", namespace="users")),
    # Your stuff: custom urls includes go here
    path("markdownx/", include("markdownx.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        path("rosetta/", include("rosetta.urls")),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

talks_tue/core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('talk/<int:pk>', views.talk, name="talk"),
    path('collection/<int:pk>', views.collection, name="collection"),
    path('collection/<int:pk>/subscribe', views.subscribe, name="subscribe"),
]

talks_tue/users/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    path(
        "login/", auth_views.login, {
            "template_name": "users/login.html"
        }, name='login'
    ),
    path(
        "logout/", auth_views.logout, {
            "next_page": "core:index",
        }, name='logout'
    ),
    path(
        "password_reset/", auth_views.password_reset, {
            "template_name": "users/password_reset.html",
            "post_reset_redirect": reverse_lazy('users:password_reset_done')
        }, name='password_reset'
    ),
    path(
        "password_reset/done/", auth_views.password_reset_done, {
            "template_name": "users/password_reset_done.html"
        }, name='password_reset_done'
    ),
    re_path(
        "^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$", auth_views.password_reset_confirm, {
            "template_name": "users/password_change.html",
        }, name='password_reset_confirm'
    ),
    path(
        "reset/done/", auth_views.password_reset_complete, {
            "template_name": "users/password_change_done.html"
        }, name='password_reset_complete'
    ),
    path(
        "password_change/", auth_views.password_change, {
            "template_name": "users/password_change.html",
            "post_change_redirect": reverse_lazy('users:password_change_done')
        }, name='password_change'
    ),
    path(
        "password_change/done/", auth_views.password_change_done, {
            "template_name": "users/password_change_done.html"
        }, name='password_change_done'
    ),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('subscription/<int:pk>', views.SubscriptionUpdateView.as_view(), name='subscription'),
    path('subscription/<int:pk>/delete', views.subscription_delete, name='subscription_delete'),
]

talks_tue/core/models.py
from django.db import models
from django.conf import settings
from django.apps import apps
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericRelation
from sequences import get_next_value
from markdownx.models import MarkdownxField

from talks_tue.revisions.utils import HasRevision
from talks_tue.users.models import Subscription

__all__ = (
    "BaseTalk", "Talk",
    "BaseCollection", "Collection",
    "Tag"
)

# ========================
# Talks
# ========================

class BaseTalk(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(verbose_name=_("Talk title"), max_length=128)
    description = MarkdownxField(verbose_name=_("Talk description"), max_length=512)
    timestamp = models.DateTimeField(verbose_name=_("Talk date"), default=now)
    name = models.CharField(verbose_name=_("Speaker's name"), max_length=128)
    about_me = MarkdownxField(verbose_name=_("Speaker's about me"), max_length=512)
    tags = models.ManyToManyField("core.Tag", verbose_name=_("Tags"), related_name="tagged_%(class)s", blank=True)
    collections = models.ManyToManyField("core.Collection", limit_choices_to={'is_meta': False}, verbose_name=_("Collections"), related_name="%(class)ss", blank=True)

    def __str__(self):
        return self.title


class Talk(HasRevision, BaseTalk):
    class Meta:
        ordering = ["timestamp"]
        verbose_name = _("talk")
        verbose_name_plural = _("talks")


# ========================
# Collections
# ========================


class BaseCollection(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(verbose_name=_("Title"), max_length=32)
    description = MarkdownxField(verbose_name=_("Description"), max_length=512)
    organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.SET_NULL, limit_choices_to={'is_staff': True}, null=True, blank=True, verbose_name=_("Organizer"), related_name="organized_%(class)ss"
    )
    editors = models.ManyToManyField(
        settings.AUTH_USER_MODEL, limit_choices_to={'is_staff': True}, verbose_name=_("Editors"), related_name="edited_%(class)ss", blank=True
    )
    is_meta = models.BooleanField(verbose_name=_("Is metacollection?"), default=False)
    meta_collections = models.ManyToManyField(
        "core.Collection", limit_choices_to={'is_meta': True}, verbose_name=_("Metacollections"), related_name="sub_%(class)ss", blank=True
    )

    @property
    def tags(self):
        return list(set(
            tag
            for talk in self.related_talks
            for tag in talk.tags.all()
        ))

    @property
    def related_talks(self):
        return list(self.talks.all()) if not self.is_meta else list(set(
            talk
            for sub_collection in self.sub_collections.all()
            for talk in sub_collection.related_talks
        ))

    def __str__(self):
        return self.title


class Collection(HasRevision, BaseCollection):
    class Meta:
        verbose_name = _("collection")
        verbose_name_plural = _("collections")

# ========================
# Misc
# ========================

class Tag(models.Model):
    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")

    name = models.CharField(verbose_name=_("Name"), max_length=32)

    def __str__(self):
        return self.name

talks_tue/revisions/models.py
from .utils import generate_revision_for
from ..core.models import Talk, Collection


__all__ = (
    "TalkRevision", "CollectionRevision"
)


@generate_revision_for(Talk)
def TalkRevision(revision_model, talk):
    revision = revision_model.objects.create(
        original=talk,
        title=talk.title,
        description=talk.description,
        timestamp=talk.timestamp,
        name=talk.name,
        about_me=talk.about_me,
    )
    revision.tags.set(talk.tags.all())
    revision.collections.set(talk.collections.all())
    return revision


@generate_revision_for(Collection)
def CollectionRevision(revision_model, collection):
    revision = revision_model.objects.create(
        original=collection,
        title=collection.title,
        description=collection.description,
        organizer=collection.organizer,
        is_meta=collection.is_meta,
    )
    revision.editors.set(collection.editors.all())
    revision.meta_collections.set(collection.meta_collections.all())
    return revision

talks_tue/users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Button, HTML, Div, Field, Row
from crispy_forms.bootstrap import FormActions, AppendedText, TabHolder, Tab, Accordion, AccordionGroup, PrependedText

from .models import User, Subscription


__all__ = (
    "UserCreationForm",
    "UserChangeForm",
    "SubscriptionChangeForm"
)


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = User
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Row(
                    Div(
                        "username",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "email",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "password1",
                        css_class="col-sm-6"
                    ),
                    Div(
                        "password2",
                        css_class="col-sm-6"
                    ),
                )
            )
        )


class UserChangeForm(forms.ModelForm):
    username = forms.CharField(label=_('Username'), disabled=True)
    email = forms.EmailField(label=_('Email address'))

    class Meta:
        model = User
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Row(
                    Div(
                        "username",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "email",
                        css_class="col"
                    ),
                ),
            )
        )


class SubscriptionChangeForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ('remind_me', 'reminder_type')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Div(
                    "remind_me",
                    css_class='col-sm-6'
                ),
                Div(
                    "reminder_type",
                    css_class='col-sm-6'
                ),
            )                
        )

talks_tue/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils.timezone import now
from django.utils.translation import gettext as _

from .models import Talk, Collection


def index(request):
    return render(
        request, "core/index.html", context={
            # "up_next": Talk.objects.filter(timestamp__gte=now()).order_by('timestamp')[:10],
            "up_next": Talk.objects.order_by('timestamp')[:10],
            "hover_messages": True
        }
    )


def talk(request, pk):
    talk = get_object_or_404(Talk, pk=pk)
    if talk.timestamp < now():
        messages.warning(request, _("The Talk is already started/over!"))
    return render(
        request, "core/talk.html", context={
            "talk": talk,
            "overdue": talk.timestamp < now(),
        }
    )


def collection(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    return render(
        request, "core/collection.html", context={
            "now": now(),
            "collection": collection,
            "talks": collection.talks.order_by('timestamp'),
            "can_subscribe": request.user.is_authenticated and not request.user.is_subscribed_to(collection)
        }
    )


@login_required
def subscribe(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    subscription = collection.subscriptions.create(user=request.user)
    return redirect('users:subscription', pk=subscription.pk)

talks_tue/users/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin
from django.views.generic import UpdateView, CreateView, DetailView, DeleteView
from django.http import HttpResponseNotAllowed
from django.core.exceptions import PermissionDenied
from django.utils.http import is_safe_url
from django.utils.translation import gettext as _, gettext_lazy as _l
from django.shortcuts import reverse, redirect, get_object_or_404

from .forms import UserCreationForm, UserChangeForm, SubscriptionChangeForm
from .models import User, Subscription



class SuccessMessageUpdateMixin:
    success_message = None

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class UserMixin(AccessMixin):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

    def get_permission_denied_message(self):
        if self.request.user.is_authenticated:
            return _("Please verfiy your account.")
        return super().get_permission_denied_message()

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_verified):
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.warning(self.request, _("For greater access please verfiy your account."))
            return redirect("core:index")
        return super().handle_no_permission()


class RegistrationView(CreateView):
    template_name = "users/register.html"
    form_class = UserCreationForm
    success_url = '/'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Check your mail to activate your account."))
        return response


class ProfileView(UserMixin, DetailView):
    template_name = "users/profile.html"


class ProfileUpdateView(UserMixin, SuccessMessageUpdateMixin, UpdateView):
    template_name = "users/update.html"
    form_class = UserChangeForm
    success_message = _l("Check your mail to validate your new email address.")

    def get_success_url(self):
        return reverse("users:profile")


class SubscriptionUpdateView(SuccessMessageUpdateMixin, AccessMixin, UpdateView):
    model = Subscription
    template_name = "users/subscription.html"
    form_class = SubscriptionChangeForm
    success_message = _l("Subscription updated.")

    def dispatch(self, request, pk):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        get_object_or_404(Subscription, pk=pk, user=request.user)
        return super().dispatch(request, pk)

    def get_success_url(self):
        return reverse("users:profile")


@login_required
def subscription_delete(request, pk):
    if request.method == "POST":
        subscription = get_object_or_404(Subscription, pk=pk)
        if subscription.user != request.user:
            raise PermissionDenied()
        subscription.delete()
        messages.success(request, _("Subscription removed."))
        redirect_to = request.POST.get('next') or request.GET.get('next')
        return redirect(
            redirect_to
            if redirect is not None and is_safe_url(redirect_to, request.get_host()) else
            "users:profile"
        )
    else:
        raise HttpResponseNotAllowed()

talks_tue/templates/core/collection.html
{% extends '../base.html' %}
{% with True as messages_displace_content %}
{% endwith %}
{% load markdownify %}
{% load i18n %}
{% block content %}
<div class="container-fluid">
    <div class="row pt-3">
        <div class="col-xs-11 col-md-10 col-lg-9 mx-auto">
            <div class="navbar border-bottom">
                <h2>{{ collection.title }}</h2>
                <a class="btn btn-primary btn-sm float-right{% if not can_subscribe %} disabled{% endif %}" href="{% url 'core:subscribe' pk=collection.pk %}" role="button" {% if not can_subscribe %}aria-disabled="true"{% endif %}>{% trans 'Subscribe' %}</a>
            </div>
            <div class="row">
                <div class="col-lg-5 col-xl-4 pt-3">
                    <div class="card border-dark">
                        <div class="card-header h-50 p-2 pl-3">
                            <h4 class="mb-0"><i class="fas fa-info-circle"></i>&nbsp;{% trans "Info" %}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Organizers’s username:" %}</small>&nbsp;<span class="h6">{{ collection.organizer.username }}</span>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Tags:" %}</small>&nbsp;<span class="h6">{% for tag in collection.tags %}{% include 'snippets/tag.html' with tag=tag %} {% endfor %}</span>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Subscribers:" %}</small>&nbsp;<span class="h6">{{ collection.subscriptions.count }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-7 col-xl-8 pt-3">
                    <div class="card border-dark">
                        <div class="card-header h-50 p-2 pl-3">
                            <h4 class="mb-0"><i class="fab fa-readme"></i>&nbsp;{% trans "Description" %}</h4>
                        </div>
                        <div class="card-body">
                            <p class="md">{{ collection.description | markdownify | escape }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="card border-dark mt-2">
                        <div class="card-header h-50 p-2 pl-3">
                            <h4 class="mb-0"><i class="fas fa-list"></i>&nbsp;{% if collection.is_meta %}{% trans "Child Collections"%}{% else %}{% trans "Talks" %}{% endif %}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if collection.is_meta %}
                                {% if collection.sub_collections.exists %}
                                    {% for sub_collection in collection.sub_collections.all %}
                                    <li class="list-group-item" onclick="window.location='{% url 'core:collection' pk=sub_collection.pk %}';" style="cursor: pointer;">
                                        <span>{{ sub_collection.title }}</span>
                                    </li>
                                    {% endfor %}
                                {% else %}
                                    <li class="list-group-item">
                                        <span class="text-muted">{% trans "This collection has no child collections." %}</span>
                                    </li>
                                {% endif %}
                            {% else %}
                                {% if collection.talks.exists %}
                                    {% for talk in collection.talks.all %}
                                        <li class="list-group-item" onclick="window.location='{% url 'core:talk' pk=talk.pk %}';" style="cursor: pointer;">
                                            <span>{{ talk.title }} <small class="text-muted">{{ talk.timestamp }}</small></span>
                                        </li>
                                    {% endfor %}
                                {% else %}
                                    <li class="list-group-item">
                                        <span class="text-muted">{% trans "This collection contains no talks." %}</span>
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card border-dark mt-2">
                        <div class="card-header h-50 p-2 pl-3">
                            <h4 class="mb-0"><i class="fas fa-list"></i>&nbsp;{% trans "Parent Collections"%}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if collection.meta_collections.exists %}
                                {% for meta_collection in collection.meta_collections.all %}
                                    <li class="list-group-item" onclick="window.location='{% url 'core:collection' pk=meta_collection.pk %}';" style="cursor: pointer;">
                                        <span>{{ meta_collection.title }}</span>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <li class="list-group-item">
                                    <span class="text-muted">{% trans "This collection has no parent collections." %}</span>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/core/index.html
{% extends '../base.html' %}
{% block content %}
{% if not request.user.is_authenticated %}
    <section class="jumbotron text-center mb-0">
        <div class="container">
            <h1 class="jumbotron-heading">Talks.tue</h1>
            <p class="lead text-muted">A simple way to find the best talks at hosted at our University for you.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Browse talks</a>
                <a href="{% url 'users:register' %}" class="btn btn-outline-secondary my-2">Register to build your profile</a>
            </p>
        </div>
    </section>
{% endif %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
        {% for talk in up_next %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">{{ talk.title }}</h5>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'core:talk' pk=talk.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                            <small class="text-muted">{{ talk.timestamp }}</small>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/core/talk.html
{% extends '../base.html' %}
{% with True as messages_displace_content %}
{% endwith %}
{% load markdownify %}
{% load i18n %}
{% block content %}
<div class="container-fluid">
    <div class="row pt-3">
        <div class="col-xs-11 col-md-10 col-lg-9 mx-auto">
            <div class="row border-bottom">
                <h2 class="text-center">{{ talk.title }}</h2>
            </div>
            <div class="row">
                <div class="col-lg-5 col-xl-4 pt-3">
                    <div class="card border-dark">
                        <div class="card-header h-50 p-2 pl-3">
                            <h4 class="mb-0"><i class="fas fa-info-circle"></i>&nbsp;{% trans "Info" %}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Speaker’s name:" %}</small>&nbsp;<span class="h6">{{ talk.name }}</span>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Date:" %}</small>&nbsp;<span class="h6">{{ talk.timestamp }}</span>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">{% trans "Tags:" %}</small>&nbsp;<span class="h6">{% for tag in talk.tags.all %}{% include 'snippets/tag.html' with tag=tag %} {% endfor %}</span>
                            </li>
                        </ul>
                    </div>
                    {% if talk.collections.exists %}
                        <div class="card border-dark mt-2">
                            <div class="card-header h-50 p-2 pl-3">
                                <h4 class="mb-0"><i class="fas fa-list"></i>&nbsp;{% trans "Collections" %}</h4>
                            </div>
                            <ul class="list-group list-group-flush">
                                {% for collection in talk.collections.all %}
                                    <li class="list-group-item" onclick="window.location='{% url 'core:collection' pk=collection.pk %}';" style="cursor: pointer;">
                                        {{ collection.title }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
                <div class="col-lg-7 col-xl-8 pt-3">
                    <div class="card border-dark">
                        <div class="card-header">
                            <ul class="nav nav-tabs card-header-tabs">
                                <li class="nav-item">
                                    <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">
                                        <i class="fab fa-readme"></i>
                                        {% trans "Description" %}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="speaker-tab" data-toggle="tab" href="#speaker" role="tab" aria-controls="speaker" aria-selected="false">
                                        <i class="fas fa-chalkboard-teacher"></i>
                                        {% trans "Speaker’s about me" %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body tab-content pt-2">
                            <div class="tab-pane active show" id="description" role="tabpanel" aria-labelledby="description-tab">
                                <p class="md">{{ talk.description | markdownify | escape }}</p>
                            </div>
                            <div class="tab-pane" id="speaker" role="tabpanel" aria-labelledby="speaker-tab">
                                <p class="md">{{ talk.about_me | markdownify | escape }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}