config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", include("talks_tue.core.urls", namespace="core")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("talks_tue.users.urls", namespace="users")),
    # Your stuff: custom urls includes go here
    path("markdownx/", include("markdownx.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        path("rosetta/", include("rosetta.urls")),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

talks_tue/core/urls.py
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('talk/<int:pk>', views.talk, name="talk"),
    path('collection/<int:pk>', views.collection, name="collection"),
    path('collection/<int:pk>/subscribe', views.subscribe, name="subscribe"),
]

talks_tue/users/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_views
from . import views


app_name = "users"

urlpatterns = [
    path(
        "login/", auth_views.login, {
            "template_name": "users/login.html"
        }, name='login'
    ),
    path(
        "logout/", auth_views.logout, {
            "next_page": "core:index",
        }, name='logout'
    ),
    path(
        "password_reset/", auth_views.password_reset, {
            "template_name": "users/password_reset.html",
            "post_reset_redirect": reverse_lazy('users:password_reset_done')
        }, name='password_reset'
    ),
    path(
        "password_reset/done/", auth_views.password_reset_done, {
            "template_name": "users/password_reset_done.html"
        }, name='password_reset_done'
    ),
    re_path(
        "^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$", auth_views.password_reset_confirm, {
            "template_name": "users/password_change.html",
        }, name='password_reset_confirm'
    ),
    path(
        "reset/done/", auth_views.password_reset_complete, {
            "template_name": "users/password_change_done.html"
        }, name='password_reset_complete'
    ),
    path(
        "password_change/", auth_views.password_change, {
            "template_name": "users/password_change.html",
            "post_change_redirect": reverse_lazy('users:password_change_done')
        }, name='password_change'
    ),
    path(
        "password_change/done/", auth_views.password_change_done, {
            "template_name": "users/password_change_done.html"
        }, name='password_change_done'
    ),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('update/', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('subscription/<int:pk>', views.SubscriptionUpdateView.as_view(), name='subscription'),
    path('subscription/<int:pk>/delete', views.subscription_delete, name='subscription_delete'),
]

talks_tue/core/models.py
from django.db import models
from django.conf import settings
from django.apps import apps
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.fields import GenericRelation
from sequences import get_next_value
from markdownx.models import MarkdownxField

from talks_tue.revisions.utils import HasRevision
from talks_tue.users.models import Subscription

__all__ = (
    "BaseTalk", "Talk",
    "BaseCollection", "Collection",
    "Tag"
)

# ========================
# Talks
# ========================

class BaseTalk(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(verbose_name=_("Talk title"), max_length=128)
    description = MarkdownxField(verbose_name=_("Talk description"), max_length=512)
    timestamp = models.DateTimeField(verbose_name=_("Talk date"), default=now)
    name = models.CharField(verbose_name=_("Speaker's name"), max_length=128)
    about_me = MarkdownxField(verbose_name=_("Speaker's about me"), max_length=512)
    tags = models.ManyToManyField("core.Tag", verbose_name=_("Tags"), related_name="tagged_%(class)s", blank=True)
    collections = models.ManyToManyField("core.Collection", limit_choices_to={'is_meta': False}, verbose_name=_("Collections"), related_name="%(class)ss", blank=True)

    def __str__(self):
        return self.title


class Talk(HasRevision, BaseTalk):
    class Meta:
        ordering = ["timestamp"]
        verbose_name = _("talk")
        verbose_name_plural = _("talks")


# ========================
# Collections
# ========================


class BaseCollection(models.Model):
    class Meta:
        abstract = True

    title = models.CharField(verbose_name=_("Title"), max_length=32)
    description = MarkdownxField(verbose_name=_("Description"), max_length=512)
    organizer = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.SET_NULL, limit_choices_to={'is_staff': True}, null=True, blank=True, verbose_name=_("Organizer"), related_name="organized_%(class)ss"
    )
    editors = models.ManyToManyField(
        settings.AUTH_USER_MODEL, limit_choices_to={'is_staff': True}, verbose_name=_("Editors"), related_name="edited_%(class)ss", blank=True
    )
    is_meta = models.BooleanField(verbose_name=_("Is metacollection?"), default=False)
    meta_collections = models.ManyToManyField(
        "core.Collection", limit_choices_to={'is_meta': True}, verbose_name=_("Metacollections"), related_name="sub_%(class)ss", blank=True
    )

    @property
    def tags(self):
        return list(set(
            tag
            for talk in self.related_talks
            for tag in talk.tags.all()
        ))

    @property
    def related_talks(self):
        return list(self.talks.all()) if not self.is_meta else list(set(
            talk
            for sub_collection in self.sub_collections.all()
            for talk in sub_collection.related_talks
        ))

    def __str__(self):
        return self.title


class Collection(HasRevision, BaseCollection):
    class Meta:
        verbose_name = _("collection")
        verbose_name_plural = _("collections")

# ========================
# Misc
# ========================

class Tag(models.Model):
    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")

    name = models.CharField(verbose_name=_("Name"), max_length=32)

    def __str__(self):
        return self.name

talks_tue/revisions/models.py
from .utils import generate_revision_for
from ..core.models import Talk, Collection


__all__ = (
    "TalkRevision", "CollectionRevision"
)


@generate_revision_for(Talk)
def TalkRevision(revision_model, talk):
    revision = revision_model.objects.create(
        original=talk,
        title=talk.title,
        description=talk.description,
        timestamp=talk.timestamp,
        name=talk.name,
        about_me=talk.about_me,
    )
    revision.tags.set(talk.tags.all())
    revision.collections.set(talk.collections.all())
    return revision


@generate_revision_for(Collection)
def CollectionRevision(revision_model, collection):
    revision = revision_model.objects.create(
        original=collection,
        title=collection.title,
        description=collection.description,
        organizer=collection.organizer,
        is_meta=collection.is_meta,
    )
    revision.editors.set(collection.editors.all())
    revision.meta_collections.set(collection.meta_collections.all())
    return revision

talks_tue/users/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Button, HTML, Div, Field, Row
from crispy_forms.bootstrap import FormActions, AppendedText, TabHolder, Tab, Accordion, AccordionGroup, PrependedText

from .models import User, Subscription


__all__ = (
    "UserCreationForm",
    "UserChangeForm",
    "SubscriptionChangeForm"
)


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = User
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Row(
                    Div(
                        "username",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "email",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "password1",
                        css_class="col-sm-6"
                    ),
                    Div(
                        "password2",
                        css_class="col-sm-6"
                    ),
                )
            )
        )


class UserChangeForm(forms.ModelForm):
    username = forms.CharField(label=_('Username'), disabled=True)
    email = forms.EmailField(label=_('Email address'))

    class Meta:
        model = User
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Row(
                    Div(
                        "username",
                        css_class="col"
                    ),
                ),
                Row(
                    Div(
                        "email",
                        css_class="col"
                    ),
                ),
            )
        )


class SubscriptionChangeForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ('remind_me', 'reminder_type')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Div(
                    "remind_me",
                    css_class='col-sm-6'
                ),
                Div(
                    "reminder_type",
                    css_class='col-sm-6'
                ),
            )                
        )

talks_tue/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils.timezone import now
from django.utils.translation import gettext as _

from .models import Talk, Collection


def index(request):
    return render(
        request, "core/index.html", context={
            # "up_next": Talk.objects.filter(timestamp__gte=now()).order_by('timestamp')[:10],
            "up_next": Talk.objects.order_by('timestamp')[:10],
            "hover_messages": True
        }
    )


def talk(request, pk):
    talk = get_object_or_404(Talk, pk=pk)
    if talk.timestamp < now():
        messages.warning(request, _("The Talk is already started/over!"))
    return render(
        request, "core/talk.html", context={
            "talk": talk,
            "overdue": talk.timestamp < now(),
        }
    )


def collection(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    return render(
        request, "core/collection.html", context={
            "now": now(),
            "collection": collection,
            "talks": collection.talks.order_by('timestamp'),
            "can_subscribe": request.user.is_authenticated and not request.user.is_subscribed_to(collection)
        }
    )


@login_required
def subscribe(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    subscription = collection.subscriptions.create(user=request.user)
    return redirect('users:subscription', pk=subscription.pk)

talks_tue/users/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin
from django.views.generic import UpdateView, CreateView, DetailView, DeleteView
from django.http import HttpResponseNotAllowed
from django.core.exceptions import PermissionDenied
from django.utils.http import is_safe_url
from django.utils.translation import gettext as _, gettext_lazy as _l
from django.shortcuts import reverse, redirect, get_object_or_404

from .forms import UserCreationForm, UserChangeForm, SubscriptionChangeForm
from .models import User, Subscription



class SuccessMessageUpdateMixin:
    success_message = None

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response


class UserMixin(AccessMixin):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

    def get_permission_denied_message(self):
        if self.request.user.is_authenticated:
            return _("Please verfiy your account.")
        return super().get_permission_denied_message()

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_verified):
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            messages.warning(self.request, _("For greater access please verfiy your account."))
            return redirect("core:index")
        return super().handle_no_permission()


class RegistrationView(CreateView):
    template_name = "users/register.html"
    form_class = UserCreationForm
    success_url = '/'
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _("Check your mail to activate your account."))
        return response


class ProfileView(UserMixin, DetailView):
    template_name = "users/profile.html"


class ProfileUpdateView(UserMixin, SuccessMessageUpdateMixin, UpdateView):
    template_name = "users/update.html"
    form_class = UserChangeForm
    success_message = _l("Check your mail to validate your new email address.")

    def get_success_url(self):
        return reverse("users:profile")


class SubscriptionUpdateView(SuccessMessageUpdateMixin, AccessMixin, UpdateView):
    model = Subscription
    template_name = "users/subscription.html"
    form_class = SubscriptionChangeForm
    success_message = _l("Subscription updated.")

    def dispatch(self, request, pk):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        get_object_or_404(Subscription, pk=pk, user=request.user)
        return super().dispatch(request, pk)

    def get_success_url(self):
        return reverse("users:profile")


@login_required
def subscription_delete(request, pk):
    if request.method == "POST":
        subscription = get_object_or_404(Subscription, pk=pk)
        if subscription.user != request.user:
            raise PermissionDenied()
        subscription.delete()
        messages.success(request, _("Subscription removed."))
        redirect_to = request.POST.get('next') or request.GET.get('next')
        return redirect(
            redirect_to
            if redirect is not None and is_safe_url(redirect_to, request.get_host()) else
            "users:profile"
        )
    else:
        raise HttpResponseNotAllowed()

talks_tue/templates/users/login.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Login' %}</h4>
                </div>
                <div class="card-body">
                    <form id="loginForm" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="loginForm">{% trans 'Login' %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/logout.html
{% extends '../base.html' %}
{% load i18n %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Logged out' %}</h4>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/password_change.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Change Password' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Change password' %}</h4>
                </div>
                <div class="card-body">
                    <form id="changeForm" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="changeForm">{% trans 'Apply changes' %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/password_change_done.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Password updated' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Password updated' %}</h4>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" href={% url "core:index" %}>{% trans 'Done' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/password_reset.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Password reset' %}</h4>
                </div>
                <div class="card-body">
                    <form id="resetForm" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="resetForm">{% trans 'Send request' %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/password_reset_confirm.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Change password' %}</h4>
                </div>
                <div class="card-body">
                    <form id="resetForm" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="resetForm">{% trans 'Apply changes' %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/password_reset_done.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Password reset request sent' %}</h4>
                </div>
                <div class="card-body">
                    <a class="btn btn-primary" href={% url "core:index" %}>{% trans 'Done' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'My Profile' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <h4>{% trans 'My Profile' %}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <small class="text-muted">{% trans 'Username' %}</small>
                                {{ object.username }}
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">{% trans 'EMail' %}</small>
                                {{ object.email }}
                            </li>
                        </ul>
                        <div class="card-footer">
                            <a class="btn btn-sm btn-primary" href="{% url 'users:update_profile' %}">{% trans 'Update profile' %}</a>
                            <a class="btn btn-sm btn-primary" href="{% url 'users:password_change' %}">{% trans 'Update password' %}</a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <h4>{% trans 'My Subscriptions' %}</h4>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if object.subscriptions.exists %}
                                {% for subscription in object.subscriptions.all %}
                                    <li class="list-group-item" onclick="window.location='{% url 'core:collection' pk=subscription.collection.pk %}';" style="cursor: pointer;">
                                        {{ subscription.collection }}
                                        <div class="float-right">
                                            <a class="btn btn-sm btn-primary" href="{% url 'users:subscription' pk=subscription.pk %}">{% trans 'Configure' %}</a>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% else %}
                                <li class="list-group-item">
                                    <span class="text-muted">{% trans "No subscriptions yet." %}</span>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Register' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Register' %}</h4>
                </div>
                <div class="card-body">
                    <form id="registrationForm" method="post">
                        {% csrf_token %}
                        {% crispy form %}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="registrationForm">{% trans 'Register' %}</button>
                    <div class="float-right">
                        <span class="text-muted">Already have an account?&nbsp;<i class="fas fa-angle-double-right"></i></span>
                        <a class="btn btn-outline-secondary" href="{% url 'users:login' %}">{% trans 'Login' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/subscription.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Update Subscription' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Update Subscription for' %} {{ object.collection.title }}</h4>
                </div>
                <div class="card-body">
                    <form id="subscriptionForm" method="post">
                        {% csrf_token %}
                        {% crispy form %}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="subscriptionForm">{% trans 'Apply changes' %}</button>
                    <div class="float-right">
                        <form id="deleteForm" action="{% url 'users:subscription_delete' pk=object.pk %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-primary" type="submit" form="deleteForm"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/subscription_delete.html
{% extends '../base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Delete Subscription' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Delete Subscription for' %} {{ object.collection.title }}</h4>
                </div>
                <div class="card-footer">
                    <form action="{% url 'users:subscription_delete' pk=object.pk %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-primary" type="submit">{% trans 'Delete' %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

talks_tue/templates/users/update.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Update Profile' %}{% endblock %}

{% block content %}
<div class="container-fluid pt-2">
    <div class="row">
        <div class="col-lg-8 col-sm-12 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans 'Update Profile' %}</h4>
                </div>
                <div class="card-body">
                    <form id="profileForm" method="post">
                        {% csrf_token %}
                        {% crispy form %}
                    </form>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" form="profileForm">{% if new %}{% trans 'Save' %}{% else %}{% trans 'Apply changes' %}{% endif %}</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}